### ISSUE TITLE
[Feature Request] Have depositors function as partial blocks for redstone purposes.

### ISSUE THREAD

**Issue by AlexTheDolphin0** [IThundxr/CreateNumismatics#38] opened 2024-04-20 03:57 UTC
At the moment, you can place a button/lever on depositors to power them with redstone the exact same way it does when coins are inserted. I think it would be a good idea for them to function similar to how stairs work, where the sides count as full blocks, but the actual stair block can't be powered by redstone. Obviously the depositors have a few more solid sides than stairs do, so it would have to be adjusted slightly. That way a singular button can't break an entire depositor system.

**Comment by AngelOfCreation** [comment] 2024-07-22 12:15
I like this idea. Good suggestion OP.

**Comment by AlexTheDolphin0** [comment] 2024-07-22 12:39
> I like this idea. Good suggestion OP.

thank you thank you

**Comment by techno-sam** [comment] 2024-08-07 18:54
Duplicate of #30

**Closed as completed by techno-sam** 2024-08-07 18:54 UTC
Labels: type: suggestion
